name: Image

on:
  push:
    branches: [main]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: [main]

env:
  VELOCITY_VERSION: "3.0.1"
  VELOCITY_MAJOR_MINOR: "3.0"

jobs:
  publish:
    name: runner / publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - id: docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
            prefix=${{ env.VELOCITY_MAJOR_MINOR }}-
          tags: |
            type=raw,value=${{ env.VELOCITY_VERSION }},prefix=
            type=raw,value=${{ env.VELOCITY_MAJOR_MINOR }},prefix=
            type=semver,pattern={{version}}
            type=ref,event=branch,enable=${{ github.event_name == 'push' }}
            type=sha,prefix=,enable=${{ github.event_name == 'pull_request' }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VELOCITY_VERSION=${{ env.VELOCITY_VERSION }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
