name: Pull Request

on:
  pull_request_target:
    branches: [main]

jobs:
  label:
    name: runner / label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/labeler@v3.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: TimonVS/pr-labeler-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
