name: Review Dog

on: [pull_request]

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: reviewdog/action-shellcheck@v1.13
        with:
          reporter: github-pr-review
          path: rootfs
          pattern: "*.sh"
          exclude: "./.git/*"
